### ISSUE TITLE
Dependencies between `ConfigNode`s

### ISSUE THREAD

**Issue by ldegen** [ldegen/irma#23]
This is similar to #11:
I  defined a custom type `GroupType` that is supposed to represent documents that are actually groups
of entities of some member element type.

In my application, I want to be able to search for both: flat lists of individual elements as well as list of groups of elements. So I need to have both types in my irma configuration, the element type, as well as the `GroupType`.  I want to do something like this:

``` yaml
types:
  element:
    index: app-elements
    attributes:
      #... attribute definitions for element type
  group: !group-type
    index: app-groups
    attributes:
      # ... there may be attributes specific to the group, but not to the child elements
    # special field containing the member elements
    membersField: children
    # I do not want to redundantly specify the attributes of the 
    # child elements. I just want to say: they are of type 'element'
    memberType: element
   
```

My idea was that during initialization the `GroupType` would look at the `memberType` and
generate its own nested attribute basically by prefixing attribute names with the `membersField`-name.
(There are a couple of other things to look after, but that's about the basic idea of it.)

Unfortunately, this does not work with the way the configuration is currently processed. During the initialization of the `GroupType`, I would need access to the (already processed) type `element`, but
in reality, all I have is its name, i.e. `'element'`. There may (at this point) not even exist a sibling type of that name. 

In #11, I tried to solve this, but eventually gave up because it just made everything more complex. But it seems that these kind of problems keep haunting me. We need an elegant solution.
