### ISSUE TITLE
Make field metadata available to plugins

### ISSUE THREAD

**Issue by ldegen** [ldegen/irma#33]
I am customizing the behavior of a multi-match-query, specifically, the semantics of DQUOT and SQUOT nodes. 
These nodes represent explicit phrases (enclosed in single and double quotes respectively).
I want those phrases to apply to certain index (sub-)fields that are *NOT* used by the normal mutli-match clauses.
On the other hand, however, I want to be able to use field qualifiers. 

Let's look at this example:

``` yaml
searchSemantics: !multi-match-query
  fieldQualifiers:
    title: ["title", "title.deompound"]
  customize:
    DQUOT: !coffee |
    (operands, cx, orig)->
       # I want quoted phrases to only be matched in .raw subfields
       # ??? how to do it ???
attributes:
  - !fulltext
    field: title
    includeSubfields:
       decompound: 0.7

  - !fulltext
    field: abstract
    includeSubfields:
       decompound: 0.7

```

Further assume that there are two further sub-fields `title.raw` and `abstract.raw` specifically for phrase queries, that use another analyzer. I did not add those to the `!fulltext`-attributes, because I do not want "normal" query clauses to be matched there.

What happens if we run a query `title:"special case"` which would be parsed to `[QLF, "title", [DQUOT, "special case"]]`.
In the initial context, we would start of with all fields that are known to any of the `!fulltext`-attributes: 
```
["title^1", "title.decompound^0.7", "abstract^1.0","abstract.decompound^0.7"]
```
The QLF-Node will filter the fields, which correctly yields
```
["title^1", "title.decompound^0.7"]
```

Now, for the DQUOT-Node, I need some custom logic that somehow detects that I need to change this to
```
["title.raw"]
``` 
before applying the phrase match. 

How would I accomplish that?
