### ISSUE TITLE
Placeholder substitution in configuration files

### ISSUE THREAD

**Issue by ldegen** [ldegen/irma#8]
It would be great if there was some way to use placeholders in config variables:

``` yaml
proxy:
  /api:
    host: "https://${MY_DEV_STAGE}:443/api"
```

They could be substituted with enironment variables, command-line options, or maybe the current settings.
(the latter might pose some difficulties...)

I *think* this could be implemented as a config-type.
